### ISSUE TITLE
binder_design.py is out of sync with esm 3.4.0

### ISSUE THREAD

**Issue by Gu-SeongHoe** [evolutionaryscale/esm#395]
Hi,
thank you for this great work and making it publicly available

Running `cookbook/tutorials/binder_design.py` against esm 3.4.0 (PyPI)
hits two API mismatches.
Environment: esm 3.4.0, transformers 4.57.6, torch 2.11.0+cu130,
Python 3.12, Tutorial file from tag v3.4.0 (827ec12).

**1. `_esmc` → `esmc`**

`_load_hf_model` (line 1236) does `assert model._esmc is not None`,
but `EsmFold2ExperimentalModel` now exposes `esmc`:

    AttributeError: 'EsmFold2ExperimentalModel' object has no attribute '_esmc'

Affects lines 1236, 1237, 1238, 1312, 1315. Patched locally with
`s/\._esmc\b/.esmc/g`.

**2. Removed forward kwargs**

After that patch, `fold_and_get_distogram` (line 703) passes
`calculate_confidence`, `disto_cond`, `disto_cond_mask`, which
`EsmFold2ExperimentalModel.forward()` no longer accepts:

    TypeError: EsmFold2ExperimentalModel.forward() got unexpected
    keyword argument(s) ['calculate_confidence', 'disto_cond', 'disto_cond_mask']

None of the three appear anywhere in `esm/models/esmfold2/experimental.py`.

Is `binder_design.py` expected to work with 3.4.0, or should it be
pinned to an earlier esm version? I'd rather not just drop the kwargs
since `disto_cond` looks load-bearing for the design loop.

Thanks!

**Comment by faustomilletari** [comment]
Hello, thank you very much for reporting this issue. We are addressing it right now and this will be reflected on main (asap) and in the next version.

**Comment by faustomilletari** [comment]
for now, my recommendation is to work off a previous hash of the main branch. a hash that should work fine is: 917af90b624535eed1e072d343c717e3ec11fef4

**Comment by Gu-SeongHoe** [comment]
Thanks for the quick response — I'll work off 917af90 in the meantime.

**Comment by Gu-SeongHoe** [comment]
Thanks — 917af90 gets past both API mismatches.
But `COMPILE = True` now fails in torch inductor's pad_mm pass:

```
torch/_inductor/fx_passes/pad_mm.py → should_pad_addmm → do_bench
RuntimeError: self and mat2 must have the same dtype, but got BFloat16 and Float
```

Reproduces on torch 2.6.0+cu124, 2.11.0+cu130 and 2.13.0+cu130 — including
2.6.0, which is what pixi.lock pins at this commit.

Which torch version is `COMPILE = True` validated against?
